---
title: "Hugh E. Jones"
about:
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com/H3Jones
    - icon: linkedin
      text: linkedin
      href: https://linkedin.com/in/hugh-e-jones
---

## About me

I am passionate about using my data and analytical science skills
to process and analyse large datasets.

I am currently finishing my PhD at the
University of Warwick, where the focus of my research is the study of base oils
and other complex mixtures by Fourier transform ion cyclotron resonance (FTICR)
mass spectrometry (MS).

In addition to my research, I develop both new R
routines and applications ([see some here](projects.qmd)), to support both my own and colleagues research
activities, as well as the maintenance and continual development of critical
software tools used by the wider research group.

## Education

September 2018 - Ongoing | PhD in Analytical Science | University of Warwick

September 2014 - June 2018 | Master of Chemistry (MChem) 2:1 | University of Warwick